from typing import List, Dict, Optional
import os
import chainlit as cl
from agno.agent import Agent
from agno.models.openai import OpenAIChat
from agno.models.google import Gemini
from agno.media import Image
from linkup import LinkupClient
from chainlit.input_widget import Select
from prompt import PRESCRIPTION_AGENT_PROMPT


DEFAULT_OPENAI_MODEL = "o4-mini"
DEFAULT_GEMINI_MODEL = "gemini-2.0-flash"

linkup_client = LinkupClient(api_key=os.environ["LINKUP_API_KEY"])

# Model options for the chat settings
MODEL_OPTIONS = {
    "OpenAI o4-mini (Reasoning)": {
        "provider": "openai",
        "model_id": "o4-mini",
        "reasoning": True
    },
    "Gemini 2.0 Flash": {
        "provider": "google",
        "model_id": "gemini-2.0-flash",
        "reasoning": False
    },
    "Gemini 2.0 Flash (Experimental)": {
        "provider": "google",
        "model_id": "gemini-2.0-flash-exp",
        "reasoning": False
    }
}


# @cl.password_auth_callback
# def auth_callback(username: str, password: str):
#     # Fetch the user matching username from your database
#     # and compare the hashed password with the value stored in the database
#     if (username, password) == ("admin", "admin"):
#         return cl.User(
#             identifier="admin", metadata={"role": "admin", "provider": "credentials"}
#         )
#     else:
#         return None


def _extract_agno_images_from_message(msg: cl.Message) -> List[Image]:
    """
    Extract Agno Image objects from message elements.
    """
    images = []
    for element in getattr(msg, "elements", []) or []:
        mime = getattr(element, "mime", None)
        if mime and isinstance(mime, str) and mime.startswith("image/"):
            path = getattr(element, "path", None)
            if path and isinstance(path, str) and os.path.exists(path):
                images.append(Image(filepath=path))
    return images


@cl.oauth_callback
def oauth_callback(
        provider_id: str,
        token: str,  raw_user_data: Dict[str, str],
        default_user: cl.User,
) -> Optional[cl.User]:
    return default_user


@cl.on_chat_resume
async def on_chat_resume(thread):
    pass


# Available commands in the UI
COMMANDS = [
    {
        "id": "Search",
        "icon": "globe",
                "description": "Find on the web",
                "button": True,
                "persistent": True
    },
]


async def search_web(query: str, depth: str = "deep") -> str:
    """
    Search the web using Linkup SDK

    Args:
            query: The search query string
            depth: Search depth ("standard" or "deep")

    Returns:
            Formatted search results as markdown text
    """
    try:
        search_results = linkup_client.search(
            query=query,
            depth=depth,
            output_type="searchResults",
        )

        formatted_text = "Search results:\n\n"

        for i, result in enumerate(search_results.results, 1):
            formatted_text += f"{i}. **{result.name}**\n"
            formatted_text += f"   URL: {result.url}\n"
            formatted_text += f"   {result.content}\n\n"

        return formatted_text
    except Exception as e:
        return f"Search failed: {str(e)}"


# Define the search tool for the agent
def search_web_tool(query: str, depth: str = "deep") -> str:
    """Search the web for real-time information."""
    import asyncio
    loop = asyncio.new_event_loop()
    asyncio.set_event_loop(loop)
    try:
        return loop.run_until_complete(search_web(query, depth))
    finally:
        loop.close()


def create_agent(model_name: str = "OpenAI o4-mini (Reasoning)"):
    """Create an agent based on the selected model."""
    model_config = MODEL_OPTIONS.get(
        model_name, MODEL_OPTIONS["OpenAI o4-mini (Reasoning)"])

    if model_config["provider"] == "openai":
        model = OpenAIChat(
            id=model_config["model_id"],
            api_key=os.getenv("OPENAI_API_KEY")
        )
    else:  # google
        model = Gemini(
            id=model_config["model_id"],
            api_key=os.getenv("GOOGLE_API_KEY")
        )

    # Add model signature to instructions
    model_signature = f"\n\nIMPORTANT: At the end of EVERY response, you MUST add a new line and then print exactly: 'Response generated by {model_config['model_id']}'"

    agent = Agent(
        model=model,
        description="You are an AI Senior Consultant Pharmacist with extensive clinical experience, serving as a mentor and guide to a team of pharmacists ranging from interns to senior practitioners. Your role is to analyze medical prescriptions, clinic bills, OPD invoices, and medical receipts with the highest level of accuracy and clinical insight.",
        # instructions=PRESCRIPTION_AGENT_PROMPT + model_signature,
        instructions=PRESCRIPTION_AGENT_PROMPT,
        tools=[search_web_tool],
        add_history_to_messages=True,
        markdown=True,
        reasoning=model_config.get("reasoning", False),
        reasoning_max_steps=10 if model_config.get(
            "reasoning", False) else None,
    )

    return agent


@cl.on_chat_start
async def on_chat_start():
    """Initialize the chat session and create the agent."""

    # Send chat settings
    settings = await cl.ChatSettings(
        [
            Select(
                id="Model",
                label="Model",
                values=list(MODEL_OPTIONS.keys()),
                initial_index=0,
            ),
        ]
    ).send()

    # Create default agent
    agent = create_agent()

    # Store agent in session
    cl.user_session.set("agent", agent)
    cl.user_session.set("chat_messages", [])
    cl.user_session.set("current_model", "OpenAI o4-mini (Reasoning)")

    # Set available commands
    await cl.context.emitter.set_commands(COMMANDS)


@cl.on_settings_update
async def setup_agent(settings):
    """Handle settings update to switch between models."""
    selected_model = settings["Model"]
    current_model = cl.user_session.get("current_model")

    # Only recreate agent if model changed
    if selected_model != current_model:
        # Show model switching message
        await cl.Message(content=f"Switching to {selected_model}...").send()

        # Create new agent with selected model
        agent = create_agent(selected_model)

        # Update session
        cl.user_session.set("agent", agent)
        cl.user_session.set("current_model", selected_model)

        # Confirm model switch
        await cl.Message(content=f"✅ Now using **{selected_model}**").send()


@cl.on_message
async def on_message(message: cl.Message):
    """Handle incoming messages and images from the user."""

    # Get the agent from session
    agent = cl.user_session.get("agent")

    # Extract images from uploaded files
    images = _extract_agno_images_from_message(message)

    # Show uploaded images in chat
    for i, element in enumerate(message.elements or []):
        if "image" in getattr(element, "mime", ""):
            await cl.Message(
                content=f"✅ Received image: **{element.name}**",
                elements=[
                    cl.Image(
                        name=element.name,
                        path=element.path,
                        display="inline"
                    )
                ]
            ).send()

    # Prepare the user's query
    user_query = message.content

    # If no specific question is asked with the image, provide a general analysis
    if images and not user_query.strip():
        user_query = PRESCRIPTION_AGENT_PROMPT

    # Handle explicit search command
    if message.command == "Search" and user_query:
        user_query = f"Please search the web for: {user_query}"

        # Create a message for streaming the response
    response_msg = cl.Message(content="")
    await response_msg.send()

    # Show thinking indicator for reasoning models
    thinking_msg = None
    if agent.reasoning:
        current_model = cl.user_session.get("current_model", "Unknown Model")
        thinking_msg = cl.Message(content=f"🤔 {current_model} is thinking...")
        await thinking_msg.send()

    try:
        # Run the agent with streaming
        response_iterator = await cl.make_async(agent.run)(
            user_query,
            images=images,
            stream=True
        )

        # Track if we've started receiving actual content
        content_started = False

        # Stream the response chunks
        for chunk in response_iterator:
            # Extract content from the chunk
            content = None
            if chunk and hasattr(chunk, 'content'):
                content = chunk.content
            elif chunk and hasattr(chunk, 'get_content_as_string'):
                content = chunk.get_content_as_string()

            if content:
                # Remove thinking message once content starts
                if not content_started and thinking_msg:
                    await thinking_msg.remove()
                    thinking_msg = None
                    content_started = True

                await response_msg.stream_token(content)

        # Finalize the message
        await response_msg.update()

    except Exception as stream_error:
        # Fallback to non-streaming if streaming fails
        print(f"Streaming failed, using non-streaming mode: {stream_error}")

        try:
            # Remove thinking message if it exists
            if thinking_msg:
                await thinking_msg.remove()

            # Run without streaming
            response = await cl.make_async(agent.run)(
                user_query,
                images=images,
                stream=False
            )

            # Get the content from the response
            if hasattr(response, 'content'):
                content = response.content
            elif hasattr(response, 'get_content'):
                content = response.get_content()
            else:
                content = str(response)

            # Display the full response at once
            await response_msg.stream_token(content)
            await response_msg.update()

        except Exception as e:
            # Remove thinking message if it exists
            if thinking_msg:
                await thinking_msg.remove()

            # Handle any errors gracefully
            error_msg = f"❌ An error occurred: {str(e)}"
            await cl.Message(content=error_msg).send()
